/*
 * generated by Xtext
 */
package org.xtext.example.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.services.SimpleJavaGrammarAccess;

public class SimpleJavaParser extends AbstractContentAssistParser {
	
	@Inject
	private SimpleJavaGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.ui.contentassist.antlr.internal.InternalSimpleJavaParser createParser() {
		org.xtext.example.ui.contentassist.antlr.internal.InternalSimpleJavaParser result = new org.xtext.example.ui.contentassist.antlr.internal.InternalSimpleJavaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getImport_statementAccess().getAlternatives_2(), "rule__Import_statement__Alternatives_2");
					put(grammarAccess.getType_declarationAccess().getAlternatives_1(), "rule__Type_declaration__Alternatives_1");
					put(grammarAccess.getClass_declarationAccess().getAlternatives_6(), "rule__Class_declaration__Alternatives_6");
					put(grammarAccess.getField_declarationAccess().getAlternatives(), "rule__Field_declaration__Alternatives");
					put(grammarAccess.getField_declarationAccess().getAlternatives_0_1(), "rule__Field_declaration__Alternatives_0_1");
					put(grammarAccess.getMethod_declarationAccess().getAlternatives_7(), "rule__Method_declaration__Alternatives_7");
					put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
					put(grammarAccess.getVariable_declarationAccess().getAlternatives_1(), "rule__Variable_declaration__Alternatives_1");
					put(grammarAccess.getVariable_declarationAccess().getAlternatives_4(), "rule__Variable_declaration__Alternatives_4");
					put(grammarAccess.getVariable_declaratorAccess().getAlternatives(), "rule__Variable_declarator__Alternatives");
					put(grammarAccess.getVariable_initializerAccess().getAlternatives(), "rule__Variable_initializer__Alternatives");
					put(grammarAccess.getFor_statementAccess().getAlternatives_2(), "rule__For_statement__Alternatives_2");
					put(grammarAccess.getSwitch_statementAccess().getAlternatives_5(), "rule__Switch_statement__Alternatives_5");
					put(grammarAccess.getCreating_expressionAccess().getAlternatives_1(), "rule__Creating_expression__Alternatives_1");
					put(grammarAccess.getExp_auxAccess().getAlternatives(), "rule__Exp_aux__Alternatives");
					put(grammarAccess.getExpressionAccess().getAlternatives_0(), "rule__Expression__Alternatives_0");
					put(grammarAccess.getExpression_auxAccess().getAlternatives_0(), "rule__Expression_aux__Alternatives_0");
					put(grammarAccess.getExpression_auxAccess().getAlternatives_0_0(), "rule__Expression_aux__Alternatives_0_0");
					put(grammarAccess.getExpression_auxAccess().getOperadorAlternatives_0_2_0(), "rule__Expression_aux__OperadorAlternatives_0_2_0");
					put(grammarAccess.getExpression_auxAccess().getAlternatives_0_3_0(), "rule__Expression_aux__Alternatives_0_3_0");
					put(grammarAccess.getExpression_auxAccess().getAlternatives_0_4(), "rule__Expression_aux__Alternatives_0_4");
					put(grammarAccess.getExpression_auxAccess().getOperadorAlternatives_0_4_0_0_0(), "rule__Expression_aux__OperadorAlternatives_0_4_0_0_0");
					put(grammarAccess.getExpression_auxAccess().getOperadorAlternatives_0_4_2_0_0(), "rule__Expression_aux__OperadorAlternatives_0_4_2_0_0");
					put(grammarAccess.getExpression_auxAccess().getOperadorAlternatives_0_4_3_0_0(), "rule__Expression_aux__OperadorAlternatives_0_4_3_0_0");
					put(grammarAccess.getMais_auxAccess().getAlternatives(), "rule__Mais_aux__Alternatives");
					put(grammarAccess.getCreating_auxAccess().getAlternatives(), "rule__Creating_aux__Alternatives");
					put(grammarAccess.getLiteral_expressionAccess().getAlternatives(), "rule__Literal_expression__Alternatives");
					put(grammarAccess.getLogical_expressionAccess().getAlternatives(), "rule__Logical_expression__Alternatives");
					put(grammarAccess.getNumeric_expressionAccess().getOperadorAlternatives_0_0(), "rule__Numeric_expression__OperadorAlternatives_0_0");
					put(grammarAccess.getArglistAccess().getAlternatives(), "rule__Arglist__Alternatives");
					put(grammarAccess.getType_specifierAccess().getAlternatives(), "rule__Type_specifier__Alternatives");
					put(grammarAccess.getTypeAccess().getAlternatives_0(), "rule__Type__Alternatives_0");
					put(grammarAccess.getMODIFIERAccess().getAlternatives(), "rule__MODIFIER__Alternatives");
					put(grammarAccess.getCompilation_unitAccess().getGroup(), "rule__Compilation_unit__Group__0");
					put(grammarAccess.getPackage_statementAccess().getGroup(), "rule__Package_statement__Group__0");
					put(grammarAccess.getImport_statementAccess().getGroup(), "rule__Import_statement__Group__0");
					put(grammarAccess.getType_declarationAccess().getGroup(), "rule__Type_declaration__Group__0");
					put(grammarAccess.getDoc_commentAccess().getGroup(), "rule__Doc_comment__Group__0");
					put(grammarAccess.getClass_declarationAccess().getGroup(), "rule__Class_declaration__Group__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_3(), "rule__Class_declaration__Group_3__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_4(), "rule__Class_declaration__Group_4__0");
					put(grammarAccess.getClass_declarationAccess().getGroup_4_2(), "rule__Class_declaration__Group_4_2__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup(), "rule__Interface_declaration__Group__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup_3(), "rule__Interface_declaration__Group_3__0");
					put(grammarAccess.getInterface_declarationAccess().getGroup_3_2(), "rule__Interface_declaration__Group_3_2__0");
					put(grammarAccess.getField_declarationAccess().getGroup_0(), "rule__Field_declaration__Group_0__0");
					put(grammarAccess.getMethod_declarationAccess().getGroup(), "rule__Method_declaration__Group__0");
					put(grammarAccess.getMethod_declarationAccess().getGroup_6(), "rule__Method_declaration__Group_6__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getParameterAccess().getGroup_2(), "rule__Parameter__Group_2__0");
					put(grammarAccess.getParameter_listAccess().getGroup(), "rule__Parameter_list__Group__0");
					put(grammarAccess.getParameter_listAccess().getGroup_1(), "rule__Parameter_list__Group_1__0");
					put(grammarAccess.getStatement_blockAccess().getGroup(), "rule__Statement_block__Group__0");
					put(grammarAccess.getStatementAccess().getGroup_1(), "rule__Statement__Group_1__0");
					put(grammarAccess.getStatementAccess().getGroup_9(), "rule__Statement__Group_9__0");
					put(grammarAccess.getStatementAccess().getGroup_10(), "rule__Statement__Group_10__0");
					put(grammarAccess.getStatementAccess().getGroup_11(), "rule__Statement__Group_11__0");
					put(grammarAccess.getStatementAccess().getGroup_12(), "rule__Statement__Group_12__0");
					put(grammarAccess.getStatementAccess().getGroup_13(), "rule__Statement__Group_13__0");
					put(grammarAccess.getStatementAccess().getGroup_14(), "rule__Statement__Group_14__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup(), "rule__Variable_declaration__Group__0");
					put(grammarAccess.getVariable_declarationAccess().getGroup_3(), "rule__Variable_declaration__Group_3__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup_0(), "rule__Variable_declarator__Group_0__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup_1(), "rule__Variable_declarator__Group_1__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup_1_1(), "rule__Variable_declarator__Group_1_1__0");
					put(grammarAccess.getVariable_declaratorAccess().getGroup_1_2(), "rule__Variable_declarator__Group_1_2__0");
					put(grammarAccess.getVariable_initializerAccess().getGroup_1(), "rule__Variable_initializer__Group_1__0");
					put(grammarAccess.getVariable_initializerAccess().getGroup_1_1(), "rule__Variable_initializer__Group_1_1__0");
					put(grammarAccess.getVariable_initializerAccess().getGroup_1_1_1(), "rule__Variable_initializer__Group_1_1_1__0");
					put(grammarAccess.getIf_statementAccess().getGroup(), "rule__If_statement__Group__0");
					put(grammarAccess.getIf_statementAccess().getGroup_5(), "rule__If_statement__Group_5__0");
					put(grammarAccess.getIf_statementAccess().getGroup_5_0(), "rule__If_statement__Group_5_0__0");
					put(grammarAccess.getDo_statementAccess().getGroup(), "rule__Do_statement__Group__0");
					put(grammarAccess.getWhile_statementAccess().getGroup(), "rule__While_statement__Group__0");
					put(grammarAccess.getFor_statementAccess().getGroup(), "rule__For_statement__Group__0");
					put(grammarAccess.getFor_statementAccess().getGroup_2_1(), "rule__For_statement__Group_2_1__0");
					put(grammarAccess.getTry_statementAccess().getGroup(), "rule__Try_statement__Group__0");
					put(grammarAccess.getTry_statementAccess().getGroup_2(), "rule__Try_statement__Group_2__0");
					put(grammarAccess.getTry_statementAccess().getGroup_2_0(), "rule__Try_statement__Group_2_0__0");
					put(grammarAccess.getTry_statementAccess().getGroup_3(), "rule__Try_statement__Group_3__0");
					put(grammarAccess.getTry_statementAccess().getGroup_3_0(), "rule__Try_statement__Group_3_0__0");
					put(grammarAccess.getSwitch_statementAccess().getGroup(), "rule__Switch_statement__Group__0");
					put(grammarAccess.getSwitch_statementAccess().getGroup_5_0(), "rule__Switch_statement__Group_5_0__0");
					put(grammarAccess.getSwitch_statementAccess().getGroup_5_1(), "rule__Switch_statement__Group_5_1__0");
					put(grammarAccess.getConstructor_declarationAccess().getGroup(), "rule__Constructor_declaration__Group__0");
					put(grammarAccess.getStatic_initializerAccess().getGroup(), "rule__Static_initializer__Group__0");
					put(grammarAccess.getCreating_expressionAccess().getGroup(), "rule__Creating_expression__Group__0");
					put(grammarAccess.getCreating_expressionAccess().getGroup_1_0(), "rule__Creating_expression__Group_1_0__0");
					put(grammarAccess.getCreating_expressionAccess().getGroup_1_1(), "rule__Creating_expression__Group_1_1__0");
					put(grammarAccess.getCreating_expressionAccess().getGroup_1_1_1(), "rule__Creating_expression__Group_1_1_1__0");
					put(grammarAccess.getCreating_expressionAccess().getGroup_1_1_2(), "rule__Creating_expression__Group_1_1_2__0");
					put(grammarAccess.getCreating_expressionAccess().getGroup_1_2(), "rule__Creating_expression__Group_1_2__0");
					put(grammarAccess.getExp_auxAccess().getGroup_0(), "rule__Exp_aux__Group_0__0");
					put(grammarAccess.getExp_auxAccess().getGroup_1(), "rule__Exp_aux__Group_1__0");
					put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
					put(grammarAccess.getExpressionAccess().getGroup_0_9(), "rule__Expression__Group_0_9__0");
					put(grammarAccess.getExpression_auxAccess().getGroup(), "rule__Expression_aux__Group__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_0_0(), "rule__Expression_aux__Group_0_0_0__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_0_2(), "rule__Expression_aux__Group_0_0_2__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_0_3(), "rule__Expression_aux__Group_0_0_3__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_0_4(), "rule__Expression_aux__Group_0_0_4__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_1(), "rule__Expression_aux__Group_0_1__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_3(), "rule__Expression_aux__Group_0_3__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_4_0(), "rule__Expression_aux__Group_0_4_0__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_4_1(), "rule__Expression_aux__Group_0_4_1__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_4_2(), "rule__Expression_aux__Group_0_4_2__0");
					put(grammarAccess.getExpression_auxAccess().getGroup_0_4_3(), "rule__Expression_aux__Group_0_4_3__0");
					put(grammarAccess.getNewBlockAccess().getGroup(), "rule__NewBlock__Group__0");
					put(grammarAccess.getCreating_auxAccess().getGroup_0(), "rule__Creating_aux__Group_0__0");
					put(grammarAccess.getCreating_auxAccess().getGroup_1(), "rule__Creating_aux__Group_1__0");
					put(grammarAccess.getCreating_auxAccess().getGroup_1_0(), "rule__Creating_aux__Group_1_0__0");
					put(grammarAccess.getCreating_auxAccess().getGroup_1_1(), "rule__Creating_aux__Group_1_1__0");
					put(grammarAccess.getAuxAccess().getGroup(), "rule__Aux__Group__0");
					put(grammarAccess.getLogical_expressionAccess().getGroup_0(), "rule__Logical_expression__Group_0__0");
					put(grammarAccess.getBit_expressionAccess().getGroup(), "rule__Bit_expression__Group__0");
					put(grammarAccess.getNumeric_expressionAccess().getGroup(), "rule__Numeric_expression__Group__0");
					put(grammarAccess.getArglistAccess().getGroup_0(), "rule__Arglist__Group_0__0");
					put(grammarAccess.getArglistAccess().getGroup_0_1(), "rule__Arglist__Group_0_1__0");
					put(grammarAccess.getArglistAccess().getGroup_1(), "rule__Arglist__Group_1__0");
					put(grammarAccess.getArglistAccess().getGroup_2(), "rule__Arglist__Group_2__0");
					put(grammarAccess.getArglistAccess().getGroup_2_2(), "rule__Arglist__Group_2_2__0");
					put(grammarAccess.getNameAccess().getGroup(), "rule__Name__Group__0");
					put(grammarAccess.getPackage_name_auxAccess().getGroup(), "rule__Package_name_aux__Group__0");
					put(grammarAccess.getTypeAccess().getGroup(), "rule__Type__Group__0");
					put(grammarAccess.getTypeAccess().getGroup_1(), "rule__Type__Group_1__0");
					put(grammarAccess.getCompilation_unitAccess().getPacoteAssignment_0(), "rule__Compilation_unit__PacoteAssignment_0");
					put(grammarAccess.getCompilation_unitAccess().getImportesAssignment_1(), "rule__Compilation_unit__ImportesAssignment_1");
					put(grammarAccess.getCompilation_unitAccess().getDeclaracaoAssignment_2(), "rule__Compilation_unit__DeclaracaoAssignment_2");
					put(grammarAccess.getPackage_statementAccess().getNoomePacoteAssignment_1(), "rule__Package_statement__NoomePacoteAssignment_1");
					put(grammarAccess.getImport_statementAccess().getNomeImporteAssignment_1(), "rule__Import_statement__NomeImporteAssignment_1");
					put(grammarAccess.getType_declarationAccess().getDeclaracaoClasseAssignment_1_0(), "rule__Type_declaration__DeclaracaoClasseAssignment_1_0");
					put(grammarAccess.getType_declarationAccess().getDeclaracaoInterfaceAssignment_1_1(), "rule__Type_declaration__DeclaracaoInterfaceAssignment_1_1");
					put(grammarAccess.getDoc_commentAccess().getComentarioAssignment_1(), "rule__Doc_comment__ComentarioAssignment_1");
					put(grammarAccess.getClass_declarationAccess().getModificadoresAssignment_0(), "rule__Class_declaration__ModificadoresAssignment_0");
					put(grammarAccess.getClass_declarationAccess().getNomeClasseAssignment_2(), "rule__Class_declaration__NomeClasseAssignment_2");
					put(grammarAccess.getClass_declarationAccess().getSuperclasseAssignment_3_1(), "rule__Class_declaration__SuperclasseAssignment_3_1");
					put(grammarAccess.getClass_declarationAccess().getImplementosClasseAssignment_4_1(), "rule__Class_declaration__ImplementosClasseAssignment_4_1");
					put(grammarAccess.getClass_declarationAccess().getImplementosClasseAssignment_4_2_1(), "rule__Class_declaration__ImplementosClasseAssignment_4_2_1");
					put(grammarAccess.getClass_declarationAccess().getCorpoClasseAssignment_6_0(), "rule__Class_declaration__CorpoClasseAssignment_6_0");
					put(grammarAccess.getClass_declarationAccess().getDeclaracaoClasseAssignment_6_1(), "rule__Class_declaration__DeclaracaoClasseAssignment_6_1");
					put(grammarAccess.getInterface_declarationAccess().getModificadoresAssignment_0(), "rule__Interface_declaration__ModificadoresAssignment_0");
					put(grammarAccess.getInterface_declarationAccess().getNomeInterfaceAssignment_2(), "rule__Interface_declaration__NomeInterfaceAssignment_2");
					put(grammarAccess.getInterface_declarationAccess().getSuperinterfacesAssignment_3_1(), "rule__Interface_declaration__SuperinterfacesAssignment_3_1");
					put(grammarAccess.getInterface_declarationAccess().getSuperinterfacesAssignment_3_2_1(), "rule__Interface_declaration__SuperinterfacesAssignment_3_2_1");
					put(grammarAccess.getInterface_declarationAccess().getCorpoInterfaceAssignment_5(), "rule__Interface_declaration__CorpoInterfaceAssignment_5");
					put(grammarAccess.getField_declarationAccess().getComentarioAssignment_0_0(), "rule__Field_declaration__ComentarioAssignment_0_0");
					put(grammarAccess.getField_declarationAccess().getDeclaracaoMetodoAssignment_0_1_0(), "rule__Field_declaration__DeclaracaoMetodoAssignment_0_1_0");
					put(grammarAccess.getField_declarationAccess().getDeclaracaoConstrutorAssignment_0_1_1(), "rule__Field_declaration__DeclaracaoConstrutorAssignment_0_1_1");
					put(grammarAccess.getField_declarationAccess().getDeclaracaoVariavelAssignment_0_1_2(), "rule__Field_declaration__DeclaracaoVariavelAssignment_0_1_2");
					put(grammarAccess.getField_declarationAccess().getEstaticoAssignment_1(), "rule__Field_declaration__EstaticoAssignment_1");
					put(grammarAccess.getMethod_declarationAccess().getModificadorMetodoAssignment_0(), "rule__Method_declaration__ModificadorMetodoAssignment_0");
					put(grammarAccess.getMethod_declarationAccess().getTipoRetornoAssignment_1(), "rule__Method_declaration__TipoRetornoAssignment_1");
					put(grammarAccess.getMethod_declarationAccess().getNomeMetodoAssignment_2(), "rule__Method_declaration__NomeMetodoAssignment_2");
					put(grammarAccess.getMethod_declarationAccess().getParametrosMetodoAssignment_4(), "rule__Method_declaration__ParametrosMetodoAssignment_4");
					put(grammarAccess.getMethod_declarationAccess().getBlocoMetodoAssignment_7_0(), "rule__Method_declaration__BlocoMetodoAssignment_7_0");
					put(grammarAccess.getParameterAccess().getTipoParametroAssignment_0(), "rule__Parameter__TipoParametroAssignment_0");
					put(grammarAccess.getParameterAccess().getNomeParametroAssignment_1(), "rule__Parameter__NomeParametroAssignment_1");
					put(grammarAccess.getParameter_listAccess().getParametrosAssignment_0(), "rule__Parameter_list__ParametrosAssignment_0");
					put(grammarAccess.getParameter_listAccess().getParametrosAssignment_1_1(), "rule__Parameter_list__ParametrosAssignment_1_1");
					put(grammarAccess.getStatement_blockAccess().getCorpoAssignment_1(), "rule__Statement_block__CorpoAssignment_1");
					put(grammarAccess.getStatementAccess().getDeclaracaoVariavelAssignment_0(), "rule__Statement__DeclaracaoVariavelAssignment_0");
					put(grammarAccess.getStatementAccess().getExpressaoAssignment_1_0(), "rule__Statement__ExpressaoAssignment_1_0");
					put(grammarAccess.getStatementAccess().getNewblocoAssignment_2(), "rule__Statement__NewblocoAssignment_2");
					put(grammarAccess.getStatementAccess().getCorpoIfAssignment_3(), "rule__Statement__CorpoIfAssignment_3");
					put(grammarAccess.getStatementAccess().getCorpoDoWhileAssignment_4(), "rule__Statement__CorpoDoWhileAssignment_4");
					put(grammarAccess.getStatementAccess().getCorpoWhileAssignment_5(), "rule__Statement__CorpoWhileAssignment_5");
					put(grammarAccess.getStatementAccess().getCorpoForAssignment_6(), "rule__Statement__CorpoForAssignment_6");
					put(grammarAccess.getStatementAccess().getCorpoTryCatchAssignment_7(), "rule__Statement__CorpoTryCatchAssignment_7");
					put(grammarAccess.getStatementAccess().getCorpoSwitchCaseAssignment_8(), "rule__Statement__CorpoSwitchCaseAssignment_8");
					put(grammarAccess.getStatementAccess().getExpressaoSynchronizedAssignment_9_2(), "rule__Statement__ExpressaoSynchronizedAssignment_9_2");
					put(grammarAccess.getStatementAccess().getCorpoSynchronizeAssignment_9_4(), "rule__Statement__CorpoSynchronizeAssignment_9_4");
					put(grammarAccess.getStatementAccess().getReturnAssignment_10_1(), "rule__Statement__ReturnAssignment_10_1");
					put(grammarAccess.getStatementAccess().getExececaoAssignment_11_1(), "rule__Statement__ExececaoAssignment_11_1");
					put(grammarAccess.getStatementAccess().getBreakAssignment_13_1(), "rule__Statement__BreakAssignment_13_1");
					put(grammarAccess.getStatementAccess().getContinueAssignment_14_1(), "rule__Statement__ContinueAssignment_14_1");
					put(grammarAccess.getVariable_declarationAccess().getModificadorAssignment_0(), "rule__Variable_declaration__ModificadorAssignment_0");
					put(grammarAccess.getVariable_declarationAccess().getTipoVariavelAssignment_1_0(), "rule__Variable_declaration__TipoVariavelAssignment_1_0");
					put(grammarAccess.getVariable_declarationAccess().getDeclaracaoVariaveisAssignment_2(), "rule__Variable_declaration__DeclaracaoVariaveisAssignment_2");
					put(grammarAccess.getVariable_declarationAccess().getDeclaracaoVariaveisAssignment_3_1(), "rule__Variable_declaration__DeclaracaoVariaveisAssignment_3_1");
					put(grammarAccess.getVariable_declarationAccess().getBlocoVariavelAssignment_4_1(), "rule__Variable_declaration__BlocoVariavelAssignment_4_1");
					put(grammarAccess.getVariable_declaratorAccess().getNomeVariavelAssignment_1_0(), "rule__Variable_declarator__NomeVariavelAssignment_1_0");
					put(grammarAccess.getVariable_declaratorAccess().getOpAssignment_1_2_0(), "rule__Variable_declarator__OpAssignment_1_2_0");
					put(grammarAccess.getVariable_declaratorAccess().getValorVariavelAssignment_1_2_1(), "rule__Variable_declarator__ValorVariavelAssignment_1_2_1");
					put(grammarAccess.getVariable_initializerAccess().getExpressaoVariavelAssignment_0(), "rule__Variable_initializer__ExpressaoVariavelAssignment_0");
					put(grammarAccess.getVariable_initializerAccess().getValorVariaveisAssignment_1_1_0(), "rule__Variable_initializer__ValorVariaveisAssignment_1_1_0");
					put(grammarAccess.getVariable_initializerAccess().getValorVariaveisAssignment_1_1_1_1(), "rule__Variable_initializer__ValorVariaveisAssignment_1_1_1_1");
					put(grammarAccess.getIf_statementAccess().getEspressaoIfAssignment_2(), "rule__If_statement__EspressaoIfAssignment_2");
					put(grammarAccess.getIf_statementAccess().getBlcoIfAssignment_4(), "rule__If_statement__BlcoIfAssignment_4");
					put(grammarAccess.getIf_statementAccess().getBlocoElseAssignment_5_0_1(), "rule__If_statement__BlocoElseAssignment_5_0_1");
					put(grammarAccess.getDo_statementAccess().getBlocoDoAssignment_1(), "rule__Do_statement__BlocoDoAssignment_1");
					put(grammarAccess.getDo_statementAccess().getExpressaoWhileAssignment_4(), "rule__Do_statement__ExpressaoWhileAssignment_4");
					put(grammarAccess.getWhile_statementAccess().getExpressaoWhileAssignment_2(), "rule__While_statement__ExpressaoWhileAssignment_2");
					put(grammarAccess.getWhile_statementAccess().getBlocoWhileAssignment_4(), "rule__While_statement__BlocoWhileAssignment_4");
					put(grammarAccess.getFor_statementAccess().getDeclaracaoVariavelAssignment_2_0(), "rule__For_statement__DeclaracaoVariavelAssignment_2_0");
					put(grammarAccess.getFor_statementAccess().getExpressaoDeclaracaoAssignment_2_1_0(), "rule__For_statement__ExpressaoDeclaracaoAssignment_2_1_0");
					put(grammarAccess.getFor_statementAccess().getExpressaoForAssignment_3(), "rule__For_statement__ExpressaoForAssignment_3");
					put(grammarAccess.getFor_statementAccess().getExpressaoIncrementoAssignment_5(), "rule__For_statement__ExpressaoIncrementoAssignment_5");
					put(grammarAccess.getFor_statementAccess().getBlocoForAssignment_7(), "rule__For_statement__BlocoForAssignment_7");
					put(grammarAccess.getTry_statementAccess().getBlocoTryAssignment_1(), "rule__Try_statement__BlocoTryAssignment_1");
					put(grammarAccess.getTry_statementAccess().getParametroCatchAssignment_2_0_2(), "rule__Try_statement__ParametroCatchAssignment_2_0_2");
					put(grammarAccess.getTry_statementAccess().getBlocoCatchAssignment_2_0_4(), "rule__Try_statement__BlocoCatchAssignment_2_0_4");
					put(grammarAccess.getTry_statementAccess().getBlocoFinallyAssignment_3_0_1(), "rule__Try_statement__BlocoFinallyAssignment_3_0_1");
					put(grammarAccess.getSwitch_statementAccess().getExpressaoSwitchAssignment_2(), "rule__Switch_statement__ExpressaoSwitchAssignment_2");
					put(grammarAccess.getSwitch_statementAccess().getExpressaoCasesAssignment_5_0_1(), "rule__Switch_statement__ExpressaoCasesAssignment_5_0_1");
					put(grammarAccess.getSwitch_statementAccess().getBlocoSwitchAssignment_5_2(), "rule__Switch_statement__BlocoSwitchAssignment_5_2");
					put(grammarAccess.getConstructor_declarationAccess().getModificadorAssignment_0(), "rule__Constructor_declaration__ModificadorAssignment_0");
					put(grammarAccess.getConstructor_declarationAccess().getNomeContrutorAssignment_1(), "rule__Constructor_declaration__NomeContrutorAssignment_1");
					put(grammarAccess.getConstructor_declarationAccess().getParametrosContrutorAssignment_3(), "rule__Constructor_declaration__ParametrosContrutorAssignment_3");
					put(grammarAccess.getConstructor_declarationAccess().getBlocoConstrutorAssignment_5(), "rule__Constructor_declaration__BlocoConstrutorAssignment_5");
					put(grammarAccess.getStatic_initializerAccess().getBlocoEstaticoAssignment_1(), "rule__Static_initializer__BlocoEstaticoAssignment_1");
					put(grammarAccess.getCreating_expressionAccess().getNovoObjetoAssignment_1_0_0(), "rule__Creating_expression__NovoObjetoAssignment_1_0_0");
					put(grammarAccess.getCreating_expressionAccess().getParametrosAssignment_1_0_1(), "rule__Creating_expression__ParametrosAssignment_1_0_1");
					put(grammarAccess.getCreating_expressionAccess().getTipoObjetoAssignment_1_1_0(), "rule__Creating_expression__TipoObjetoAssignment_1_1_0");
					put(grammarAccess.getCreating_expressionAccess().getParametrosAssignment_1_1_1_0(), "rule__Creating_expression__ParametrosAssignment_1_1_1_0");
					put(grammarAccess.getCreating_expressionAccess().getExpressaoNewAssignment_1_2_1(), "rule__Creating_expression__ExpressaoNewAssignment_1_2_1");
					put(grammarAccess.getCreating_expressionAccess().getNovoAssignment_2(), "rule__Creating_expression__NovoAssignment_2");
					put(grammarAccess.getExp_auxAccess().getExpressaoAssignment_0_0(), "rule__Exp_aux__ExpressaoAssignment_0_0");
					put(grammarAccess.getExp_auxAccess().getExpressaoAssignment_1_2(), "rule__Exp_aux__ExpressaoAssignment_1_2");
					put(grammarAccess.getExpressionAccess().getLogicalAssignment_0_0(), "rule__Expression__LogicalAssignment_0_0");
					put(grammarAccess.getExpressionAccess().getNumericAssignment_0_1(), "rule__Expression__NumericAssignment_0_1");
					put(grammarAccess.getExpressionAccess().getBitAssignment_0_2(), "rule__Expression__BitAssignment_0_2");
					put(grammarAccess.getExpressionAccess().getNovoAssignment_0_3(), "rule__Expression__NovoAssignment_0_3");
					put(grammarAccess.getExpressionAccess().getLiteralAssignment_0_4(), "rule__Expression__LiteralAssignment_0_4");
					put(grammarAccess.getExpressionAccess().getIdentificadorAssignment_0_8(), "rule__Expression__IdentificadorAssignment_0_8");
					put(grammarAccess.getExpressionAccess().getExpressoesAssignment_1(), "rule__Expression__ExpressoesAssignment_1");
					put(grammarAccess.getExpression_auxAccess().getParametrosAssignment_0_0_0_1(), "rule__Expression_aux__ParametrosAssignment_0_0_0_1");
					put(grammarAccess.getExpression_auxAccess().getExpAssignment_0_0_2_1(), "rule__Expression_aux__ExpAssignment_0_0_2_1");
					put(grammarAccess.getExpression_auxAccess().getOpAssignment_0_1_0(), "rule__Expression_aux__OpAssignment_0_1_0");
					put(grammarAccess.getExpression_auxAccess().getExpAssignment_0_1_1(), "rule__Expression_aux__ExpAssignment_0_1_1");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_2(), "rule__Expression_aux__OperadorAssignment_0_2");
					put(grammarAccess.getExpression_auxAccess().getOpAssignment_0_3_0_0(), "rule__Expression_aux__OpAssignment_0_3_0_0");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_3_0_1(), "rule__Expression_aux__OperadorAssignment_0_3_0_1");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_3_0_2(), "rule__Expression_aux__OperadorAssignment_0_3_0_2");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_3_0_3(), "rule__Expression_aux__OperadorAssignment_0_3_0_3");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_3_0_4(), "rule__Expression_aux__OperadorAssignment_0_3_0_4");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_3_0_5(), "rule__Expression_aux__OperadorAssignment_0_3_0_5");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_3_0_6(), "rule__Expression_aux__OperadorAssignment_0_3_0_6");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_3_0_7(), "rule__Expression_aux__OperadorAssignment_0_3_0_7");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_3_0_8(), "rule__Expression_aux__OperadorAssignment_0_3_0_8");
					put(grammarAccess.getExpression_auxAccess().getExpAssignment_0_3_1(), "rule__Expression_aux__ExpAssignment_0_3_1");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_4_0_0(), "rule__Expression_aux__OperadorAssignment_0_4_0_0");
					put(grammarAccess.getExpression_auxAccess().getExpAssignment_0_4_0_1(), "rule__Expression_aux__ExpAssignment_0_4_0_1");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_4_1_0(), "rule__Expression_aux__OperadorAssignment_0_4_1_0");
					put(grammarAccess.getExpression_auxAccess().getExpAssignment_0_4_1_1(), "rule__Expression_aux__ExpAssignment_0_4_1_1");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_4_1_2(), "rule__Expression_aux__OperadorAssignment_0_4_1_2");
					put(grammarAccess.getExpression_auxAccess().getExpAssignment_0_4_1_3(), "rule__Expression_aux__ExpAssignment_0_4_1_3");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_4_2_0(), "rule__Expression_aux__OperadorAssignment_0_4_2_0");
					put(grammarAccess.getExpression_auxAccess().getExpAssignment_0_4_2_1(), "rule__Expression_aux__ExpAssignment_0_4_2_1");
					put(grammarAccess.getExpression_auxAccess().getOperadorAssignment_0_4_3_0(), "rule__Expression_aux__OperadorAssignment_0_4_3_0");
					put(grammarAccess.getExpression_auxAccess().getExpAssignment_0_4_3_1(), "rule__Expression_aux__ExpAssignment_0_4_3_1");
					put(grammarAccess.getExpression_auxAccess().getExpressoesAssignment_1(), "rule__Expression_aux__ExpressoesAssignment_1");
					put(grammarAccess.getMais_auxAccess().getOperadorAssignment_0(), "rule__Mais_aux__OperadorAssignment_0");
					put(grammarAccess.getMais_auxAccess().getOperadorAssignment_1(), "rule__Mais_aux__OperadorAssignment_1");
					put(grammarAccess.getCreating_auxAccess().getArgumentosAssignment_0_1(), "rule__Creating_aux__ArgumentosAssignment_0_1");
					put(grammarAccess.getAuxAccess().getEspressaoAssignment_1(), "rule__Aux__EspressaoAssignment_1");
					put(grammarAccess.getLiteral_expressionAccess().getDecimalAssignment_0(), "rule__Literal_expression__DecimalAssignment_0");
					put(grammarAccess.getLiteral_expressionAccess().getInteiroAssignment_1(), "rule__Literal_expression__InteiroAssignment_1");
					put(grammarAccess.getLiteral_expressionAccess().getL_floatAssignment_2(), "rule__Literal_expression__L_floatAssignment_2");
					put(grammarAccess.getLiteral_expressionAccess().getStringAssignment_3(), "rule__Literal_expression__StringAssignment_3");
					put(grammarAccess.getLogical_expressionAccess().getOperadorAssignment_0_0(), "rule__Logical_expression__OperadorAssignment_0_0");
					put(grammarAccess.getLogical_expressionAccess().getExpAssignment_0_1(), "rule__Logical_expression__ExpAssignment_0_1");
					put(grammarAccess.getLogical_expressionAccess().getOperadorAssignment_1(), "rule__Logical_expression__OperadorAssignment_1");
					put(grammarAccess.getLogical_expressionAccess().getOperadorAssignment_2(), "rule__Logical_expression__OperadorAssignment_2");
					put(grammarAccess.getBit_expressionAccess().getOperadorAssignment_0(), "rule__Bit_expression__OperadorAssignment_0");
					put(grammarAccess.getBit_expressionAccess().getExpressaoAssignment_1(), "rule__Bit_expression__ExpressaoAssignment_1");
					put(grammarAccess.getNumeric_expressionAccess().getOperadorAssignment_0(), "rule__Numeric_expression__OperadorAssignment_0");
					put(grammarAccess.getNumeric_expressionAccess().getExpressaoAssignment_1(), "rule__Numeric_expression__ExpressaoAssignment_1");
					put(grammarAccess.getArglistAccess().getExpressoesArgumentosAssignment_0_0(), "rule__Arglist__ExpressoesArgumentosAssignment_0_0");
					put(grammarAccess.getArglistAccess().getExpressoesArgumentosAssignment_0_1_1(), "rule__Arglist__ExpressoesArgumentosAssignment_0_1_1");
					put(grammarAccess.getArglistAccess().getTipoParametroAssignment_2_0(), "rule__Arglist__TipoParametroAssignment_2_0");
					put(grammarAccess.getArglistAccess().getNomeParametroAssignment_2_1(), "rule__Arglist__NomeParametroAssignment_2_1");
					put(grammarAccess.getArglistAccess().getTipoParametroAssignment_2_2_1(), "rule__Arglist__TipoParametroAssignment_2_2_1");
					put(grammarAccess.getArglistAccess().getNomeParametroAssignment_2_2_2(), "rule__Arglist__NomeParametroAssignment_2_2_2");
					put(grammarAccess.getNameAccess().getNomeAssignment_0(), "rule__Name__NomeAssignment_0");
					put(grammarAccess.getNameAccess().getPacoteAssignment_1(), "rule__Name__PacoteAssignment_1");
					put(grammarAccess.getPackage_name_auxAccess().getNomePacoteAssignment_1(), "rule__Package_name_aux__NomePacoteAssignment_1");
					put(grammarAccess.getPackage_name_auxAccess().getPacoteAssignment_2(), "rule__Package_name_aux__PacoteAssignment_2");
					put(grammarAccess.getType_specifierAccess().getNomeAssignment_0(), "rule__Type_specifier__NomeAssignment_0");
					put(grammarAccess.getType_specifierAccess().getNomeAssignment_1(), "rule__Type_specifier__NomeAssignment_1");
					put(grammarAccess.getType_specifierAccess().getNomeAssignment_2(), "rule__Type_specifier__NomeAssignment_2");
					put(grammarAccess.getType_specifierAccess().getNomeAssignment_3(), "rule__Type_specifier__NomeAssignment_3");
					put(grammarAccess.getType_specifierAccess().getNomeAssignment_4(), "rule__Type_specifier__NomeAssignment_4");
					put(grammarAccess.getType_specifierAccess().getNomeAssignment_5(), "rule__Type_specifier__NomeAssignment_5");
					put(grammarAccess.getType_specifierAccess().getNomeAssignment_6(), "rule__Type_specifier__NomeAssignment_6");
					put(grammarAccess.getType_specifierAccess().getNomeAssignment_7(), "rule__Type_specifier__NomeAssignment_7");
					put(grammarAccess.getTypeAccess().getPrimitivoAssignment_0_0(), "rule__Type__PrimitivoAssignment_0_0");
					put(grammarAccess.getTypeAccess().getObjetoAssignment_0_1(), "rule__Type__ObjetoAssignment_0_1");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_0(), "rule__MODIFIER__ModificadorAssignment_0");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_1(), "rule__MODIFIER__ModificadorAssignment_1");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_2(), "rule__MODIFIER__ModificadorAssignment_2");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_3(), "rule__MODIFIER__ModificadorAssignment_3");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_4(), "rule__MODIFIER__ModificadorAssignment_4");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_5(), "rule__MODIFIER__ModificadorAssignment_5");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_6(), "rule__MODIFIER__ModificadorAssignment_6");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_7(), "rule__MODIFIER__ModificadorAssignment_7");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_8(), "rule__MODIFIER__ModificadorAssignment_8");
					put(grammarAccess.getMODIFIERAccess().getModificadorAssignment_9(), "rule__MODIFIER__ModificadorAssignment_9");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.ui.contentassist.antlr.internal.InternalSimpleJavaParser typedParser = (org.xtext.example.ui.contentassist.antlr.internal.InternalSimpleJavaParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SimpleJavaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SimpleJavaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
