/*
 * generated by Xtext
 */
package org.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SimpleJavaStandaloneSetup extends SimpleJavaStandaloneSetupGenerated{

	public static void doSetup() {
		new SimpleJavaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

