/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ui.internal.SimpleJavaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SimpleJavaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SimpleJavaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SimpleJavaActivator.getInstance().getInjector(SimpleJavaActivator.ORG_XTEXT_SIMPLEJAVA);
	}
	
}
