/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SimpleJavaUiModule extends org.xtext.ui.AbstractSimpleJavaUiModule {
	public SimpleJavaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
